---
detectors:
  DuplicateMethodCall:
    max_calls: 3
  UtilityFunction:
    public_methods_only: true

exclude_paths:
  - spec
  - lib/generators/templates
  - lib/generators/mongoid/templates
  - lib/generators/rspec/templates
